labels:
  org.opencontainers.image.title: "Home Assistant Add-on: AC MQTT proxy"
  org.opencontainers.image.description: "AC MQTT proxy for home assistant."
  org.opencontainers.image.source: "https://github.com/Arbuzov/hass-broadlink-ac-mqtt"
  org.opencontainers.image.licenses: "Apache License 2.0"